### ISSUE TITLE
when load CogVideoX-5b model, it gets error as : TypeError: load_checkpoint_and_dispatch() got an unexpected keyword argument 'strict'

### ISSUE THREAD

**Issue by weihualiuhupituzi** [NUS-HPC-AI-Lab/VideoSys#250]
Does the work support the CogVideoX-5b model?

**Comment by oahzxl** [comment]
that seems package version problem

**Comment by weihualiuhupituzi** [comment]
> that seems package version problem

when I upload transformer model, it gets this problem. Do you think it relate to the diffusers module version or other modul?

**Comment by oahzxl** [comment]
we have restrict diffuser and transformer version in requirements, have you followed that? and can you provide more detail trace of the error?

**Comment by weihualiuhupituzi** [comment]
> we have restrict diffuser and transformer version in requirements, have you followed that? and can you provide more detail trace of the error?

Yes, I run the code in path: VideoSys-pab/examples/cogvideox/sample.py
and follow the requirements.txt as the git provided. I also download the CogVideoX-5b model from the CogVid git which link to Modelscope website.  Finally, we got the error below:
```
(videosys_wujx) root@dl-fa1f0874ec163affbe764b191d3922bb-r0-57f513f54c62-0:~/work/filestorage/wujx/VideoSys-pab/examples/cogvideox# python sample.py 
Traceback (most recent call last):
  File "/root/work/filestorage/wujx/VideoSys-pab/examples/cogvideox/sample.py", line 42, in <module>
    run_base()
  File "/root/work/filestorage/wujx/VideoSys-pab/examples/cogvideox/sample.py", line 8, in run_base
    engine = VideoSysEngine(config)
  File "/root/work/filestorage/wujx/VideoSys-pab/videosys/core/engine.py", line 21, in __init__
    self._init_worker(config.pipeline_cls)
  File "/root/work/filestorage/wujx/VideoSys-pab/videosys/core/engine.py", line 63, in _init_worker
    self.driver_worker = self._create_pipeline(
  File "/root/work/filestorage/wujx/VideoSys-pab/videosys/core/engine.py", line 71, in _create_pipeline
    pipeline = pipeline_cls(self.config)
  File "/root/work/filestorage/wujx/VideoSys-pab/videosys/pipelines/cogvideox/pipeline_cogvideox.py", line 142, in __init__
    transformer = CogVideoXTransformer3DModel.from_pretrained(
  File "/root/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 886, in from_pretrained
    accelerate.load_checkpoint_and_dispatch(
TypeError: load_checkpoint_and_dispatch() got an unexpected keyword argument 'strict'
(videosys_wujx) root@dl-fa1f0874ec163affbe764b191d3922bb-r0-57f513f54c62-0:~/work/filestorage/wujx/VideoSys-pab/examples/cogvideox# 

We also the check the diffuser version of  CogVid and found that ti require the version of diffusers>=0.31.0; however, in Videosys it requires the diffusers==0.30.0.  We also try to update the diffusers version but it seems not work.

Hope you can give us support, thanks ahead.
```

**Comment by oahzxl** [comment]
https://github.com/black-forest-labs/flux/issues/134 maybe this will help

**Comment by weihualiuhupituzi** [comment]
> [black-forest-labs/flux#134](https://github.com/black-forest-labs/flux/issues/134) maybe this will help

It works!!!  Thank you!

**Comment by weihualiuhupituzi** [comment]
pip install accelerate -U
