### ISSUE TITLE
读取数据报错，numworker改成0才稳定，请问是什么问题？

### ISSUE THREAD

**Issue by ersanliqiao** [NUS-HPC-AI-Lab/VideoSys#97]
Traceback (most recent call last):
  File "xx/OpenDiT-master/train.py", line 383, in <module>
    main(args)
  File xx/OpenDiT-master/train.py", line 275, in main
    batch = next(dataloader_iter)
  File "/root/miniconda3/envs/opendit/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/opendit/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1329, in _next_data
    idx, data = self._get_data()
  File "/root/miniconda3/envs/opendit/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1285, in _get_data
    success, data = self._try_get_data()
  File "/root/miniconda3/envs/opendit/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1146, in _try_get_data
    raise RuntimeError(f'DataLoader worker (pid(s) {pids_str}) exited unexpectedly') from e
RuntimeError: DataLoader worker (pid(s) 2365846) exited unexpectedly

**Comment by KKZ20** [comment]
How did you launch your script?

**Comment by ersanliqiao** [comment]
I think memory may leak, get bigger than 600G, so been killed

**Comment by ersanliqiao** [comment]
目前是发现跑几十万数据，内存一直增长

**Comment by oahzxl** [comment]
it about torch dataloader. you can use gc collect to avoid this problem

**Comment by oahzxl** [comment]
close due to inactive
